Enginewerk\EmissionBundle\Entity\FileBlock:
    repositoryClass: Enginewerk\EmissionBundle\Repository\Doctrine\FileBlockRepository
    type: entity
    table: file_block
    id:
        id:
            type: integer
            options:
                unsigned: true
            generator:
                strategy: AUTO
    fields:
        fileHash:
            type: string
            column: file_hash
            length: 41
            nullable: false

        size:
            type: integer
            column: size
            options:
                unsigned: true
            nullable: false

        rangeStart:
            type: bigint
            column: range_start
            options:
                unsigned: true
            nullable: false

        rangeEnd:
            type: bigint
            column: range_end
            options:
                unsigned: true
            nullable: false

        createdAt:
            column: createdAt
            type: datetime

        updatedAt:
            column: updatedAt
            type: datetime

    manyToOne:
        file:
            targetEntity: Enginewerk\EmissionBundle\Entity\File
            inversedBy: fileBlocks
            joinColumn:
                name: file_id
                referencedColumnName: id
            inversedBy: fileBlocks
#            onDelete: CASCADE
