language: php

php:
    - 5.6
    - 7.1

before_script:
    - cd emission && composer self-update && composer install --prefer-source --no-interaction

script:
    - ./bin/phpunit -c ./app/phpunit.xml
