services:
    enginewerk_resumable.service.resumable_file_upload_service:
        public: true
        class: Enginewerk\ResumableBundle\Service\ResumableFileUploadService
        arguments:
            - '@enginewerk_fs.service.binary_storage_service'
            - '@enginewerk_emission.service.file_view_service'
            - '@enginewerk_emission.service.file_write_service'
            - '@enginewerk_emission.service.file_read_service'
