services:
    enginewerk_emission.service.capabilities_service:
        public: true
        class: Enginewerk\EmissionBundle\Service\CapabilitiesService
        arguments: ['%app.uploader_max_chunk_size%']

    enginewerk.twig.enginewerk_extension:
        public: true
        class: Enginewerk\EmissionBundle\Twig\EmissionExtension
        tags:
            - { name: twig.extension }

    enginewerk_emission.service.file_stream_service:
        public: true
        class: Enginewerk\EmissionBundle\Service\FileStreamService
        arguments:
            - '@enginewerk_file_management.service.file_block_read_service'
            - '@enginewerk_file_management.service.file_read_service'
        calls:
            - [setLogger, ['@logger']]

    enginewerk_emission.service.file_view_service:
        public: false
        class: Enginewerk\EmissionBundle\Service\FileViewService
        arguments: ['@router']

    enginewerk_emission.service.file_service:
        public: true
        class: Enginewerk\EmissionBundle\Service\FileService
        arguments:
            - '@templating.engine.twig'
            - '@enginewerk_file_management.storage.file_storage'
            - '@enginewerk_file_management.service.file_read_service'
