services:
    enginewerk.twig.enginewerk_extension:
        class: Enginewerk\EmissionBundle\Twig\EmissionExtension
        tags:
            - { name: twig.extension }   
            
    enginewerk_emission.file_block:
        class: Enginewerk\EmissionBundle\EventListener\FileBlockSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    emission_file_storage:
        class:     Enginewerk\EmissionBundle\Storage\FileStorage
        arguments: ["@doctrine", "@enginewerk_bbs"]       