imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@EnginewerkFSBundle/Resources/config/services.yml' }
    - { resource: '@UserBundle/Resources/config/services.yml' }
    - { resource: '@OAuthBundle/Resources/config/services.yml' }

framework:
    #esi:             ~
    translator:      { fallback: '%locale%' }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_proxies: ~
    session:
        handler_id: ~
        name: EMSNSID
    fragments:       ~
    
parameters:

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        max_chunk_size: '%app.uploader_max_chunk_size%'
        company_name: '%app.company_name%'
          
# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    bundles:        
        - EnginewerkEmissionBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        server_version: 5.6

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }


doctrine_migrations:
    dir_name: '%kernel.root_dir%/migrations'
    namespace: Application\Migrations
    table_name: _doctrine_migration_versions
    name: Application Migrations

fos_user:
    db_driver: orm
    firewall_name: secure_area
    user_class: Enginewerk\UserBundle\Entity\User
    registration:
        confirmation:
            enabled:    false # change to true for required email confirmation
        form:
            type: enginewerk_user_registration            

knp_gaufrette:
    adapters:
        data_local:
            local:
                directory:  '%storage_root_directory%/local_fs/binary/'
    filesystems:
        binary_storage:
            adapter:        data_local
            alias:          binary_storage         
    stream_wrapper: ~
