security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, oauth.user_provider]
                
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    
        oauth.user_provider:
            id: hwi_oauth.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        download:
            pattern:  ^/(f|d|o)/
            security: false            
        
        secured_area:
            pattern:  ^/
            anonymous: true
            oauth:
                resource_owners:
                    google:             "/login/check-google"
                    windows_live:       "/login/check-windows-live"
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider
        
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }       
        - { path: ^/, role: ROLE_USER }
