security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #login:
        #    pattern:  ^/demo/secured/login$
        #    security: false

        download:
            pattern:  ^/(f|d|o)/
            security: false

        secured_area:
            pattern:    ^/
            #form_login:
            #    check_path: _security_check
            #    login_path: _demo_login
            #logout:
            #    path:   _demo_logout
            #    target: _demo
            #anonymous: ~
            http_basic:
                realm: "Requires login"

    access_control:
        - { path: ^/, roles: ROLE_USER }
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
