services:
    enginewerk_file_management.model.file_factory:
        public: false
        class: Enginewerk\FileManagementBundle\Model\FileFactory

    enginewerk_file_management.service.file_read_service:
        public: false
        class: Enginewerk\FileManagementBundle\Service\FileReadService
        arguments:
            - '@enginewerk_file_management.repository.file_repository'
            - '@enginewerk_file_management.repository.file_block_repository'
            - '@enginewerk_file_management.model.file_factory'

    enginewerk_file_management.repository.file_block_repository:
        public: false
        class: Enginewerk\FileManagementBundle\Repository\Doctrine\FileBlockRepository
        factory:   ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [Enginewerk\FileManagementBundle\Entity\FileBlock]

    enginewerk_file_management.repository.file_repository:
        public: false
        class: Enginewerk\FileManagementBundle\Repository\Doctrine\FileRepository
        factory:   ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [Enginewerk\FileManagementBundle\Entity\File]

    enginewerk_file_management.event_listener.file_block_subscriber:
        public: true
        class: Enginewerk\FileManagementBundle\EventListener\FileBlockSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enginewerk_file_management.event_listener.file_subscriber:
        class: Enginewerk\FileManagementBundle\EventListener\FileSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enginewerk_file_management.service.file_block_read_service:
        public: true
        class: Enginewerk\FileManagementBundle\Service\FileBlockReadService
        arguments:
            - '@enginewerk_file_management.service.file_read_service'
            - '@enginewerk_fs.service.binary_storage_service'

    enginewerk_file_management.storage.file_storage:
        public: true
        class: Enginewerk\FileManagementBundle\Storage\FileStorage
        arguments:
            - '@enginewerk_fs.service.binary_storage_service'
            - '@enginewerk_file_management.service.file_read_service'
            - '@enginewerk_file_management.service.file_write_service'
        calls:
            - [setLogger, ['@logger']]

    enginewerk_file_management.service.file_write_service:
        public: false
        class: Enginewerk\FileManagementBundle\Service\FileWriteService
        arguments:
            - '@enginewerk_file_management.repository.file_repository'
            - '@enginewerk_file_management.repository.file_block_repository'
