services:
    enginewerk_bbs:
        class:     Enginewerk\FSBundle\Storage\BinaryStorage
        arguments: ["@doctrine", "%kernel.root_dir%"] 
        
    enginewerk_fs.binary_block:
        class: Enginewerk\FSBundle\EventListener\BinaryBlockSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }            