services:
    enginewerk_emission.service.file_presentation_service:
        public: true
        class: Enginewerk\EmissionBundle\Service\FilePresentationService
        arguments:
            - '@enginewerk_emission.repository.file_repository'
            - '@enginewerk_emission.byte_formatter.script_fusion_adapter'

    enginewerk_emission.storage.file_manager:
        public: true
        class: Enginewerk\EmissionBundle\Storage\FileManager
        arguments:
            - '@enginewerk_emission.repository.file_repository'
            - '@enginewerk_emission.repository.file_block_repository'
            - '@enginewerk_emission.storage.manager.file_creation_manager'
            - '@enginewerk_fs.service.binary_storage_service'

    enginewerk_emission.storage.manager.file_creation_manager:
        class: Enginewerk\EmissionBundle\Storage\Manager\FileCreationManager
        public: true
        arguments:
            - '@enginewerk_emission.repository.file_repository'
            - '@enginewerk_resumable.common.uuid.uuid_version4generator'
            - '@enginewerk_emission.generator_adapter.native_generator_adapter'
            - '@enginewerk_user.repository_doctrine.user_repository'
            - '@enginewerk_emission.storage_configuration.configuration'
            - '@enginewerk_application.service.date_time_read_service'

    enginewerk_emission.storage_configuration.configuration:
        class: Enginewerk\EmissionBundle\Storage\Configuration\Configuration
        public: false

    enginewerk_emission.generator_adapter.native_generator_adapter:
        class: Enginewerk\EmissionBundle\Generator\Adapter\NativeGeneratorAdapter
        public: false

    enginewerk_emission.byte_formatter.script_fusion_adapter:
        public: false
        class: Enginewerk\Common\Formatter\ByteFormatter\Adapter\ScriptFusionAdapter
        arguments: ['@enginewerk_emission.byte_formatter.script_fusion']

    enginewerk_emission.byte_formatter.script_fusion:
        public: false
        class: ScriptFUSION\Byte\ByteFormatter

    enginewerk_emission.repository.file_block_repository:
        class: Enginewerk\EmissionBundle\Repository\Doctrine\FileBlockRepository
        public: false
        factory:   ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [Enginewerk\EmissionBundle\Entity\FileBlock]

    enginewerk_emission.repository.file_repository:
        class: Enginewerk\EmissionBundle\Repository\Doctrine\FileRepository
        public: false
        factory:   ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [Enginewerk\EmissionBundle\Entity\File]

    enginewerk.twig.enginewerk_extension:
        class: Enginewerk\EmissionBundle\Twig\EmissionExtension
        tags:
            - { name: twig.extension }

    enginewerk_emission.event_listener.file_block_subscriber:
        class: Enginewerk\EmissionBundle\EventListener\FileBlockSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ['@enginewerk_application.service.date_time_read_service']

    enginewerk_emission.event_listener.file_subscriber:
        class: Enginewerk\EmissionBundle\EventListener\FileSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ['@enginewerk_application.service.date_time_read_service']

    enginewerk_emission.service.file_write_service:
        public: false
        class: Enginewerk\EmissionBundle\Service\FileWriteService
        arguments:
            - '@enginewerk_emission.repository.file_repository'
            - '@enginewerk_emission.repository.file_block_repository'

    enginewerk_emission.service.file_read_service:
        public: false
        class: Enginewerk\EmissionBundle\Service\FileReadService
        arguments:
            - '@enginewerk_emission.repository.file_repository'
            - '@enginewerk_emission.repository.file_block_repository'

    enginewerk_emission.service.stream_service:
        public: true
        class: Enginewerk\EmissionBundle\Service\StreamService
        arguments:
            - '@enginewerk_emission.storage.file_finder'
            - '@enginewerk_emission.storage.file_reader'

    enginewerk_emission.storage.file_reader:
        public: false
        class: Enginewerk\EmissionBundle\Storage\FileReader
        arguments: ['@enginewerk_fs.service.binary_storage_service']

    enginewerk_emission.storage.file_finder:
        public: false
        class: Enginewerk\EmissionBundle\Storage\FileFinder
        arguments:
            - '@enginewerk_emission.repository.file_repository'
            - '@enginewerk_emission.repository.file_block_repository'
