services:
    enginewerk_stat.presentation_doctrine.file_reader:
        class: Enginewerk\StatBundle\Presentation\Doctrine\FileReader
        public: true
        arguments: ['@doctrine.orm.default_entity_manager']
